export { Camion } from './model/frontend/Camion'
export { Entrega } from './model/frontend/Entrega'
export { Flete } from './model/frontend/Flete'
export { Picking } from './model/frontend/Picking'
export { Tienda } from './model/frontend/Tienda'
export { Tipo } from './model/frontend/Tipo'
export { Viaje } from './model/frontend/Viaje'
